dist: bionic
sudo: false

services:
  - docker

before_install:
  - sudo service docker restart

install:
  - docker build -t nginx-brotli .
  - docker run -d -p 80:80 nginx-brotli

script:
  - ./.travis.sh

